[package]
name = "ioc-rs"
version = "0.0.1"
authors = ["Markus Ineichen <kusi.ineichen@gmail.com>"]
description = "Inversion of control inspired by .Net's Microsoft.Extensions.DependencyInjection"
repository = "https://github.com/mineichen/ioc_rs"
keywords = ["ioc", "dependency-injection", "dynamic", "inversion-of-control", "di"]
categories = ["config"]
readme = "README.md"
license = "MIT"
edition = "2018"

[dependencies]
once_cell = {version = "1.5", features = []}
